# Generated by Django 4.2 on 2024-11-22 09:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculater',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
