# Generated by Django 4.2 on 2024-11-26 16:42

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculater',
            name='date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='calculater',
            name='description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
