# Generated by Django 4.2 on 2024-11-26 16:42

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_alter_calculater_date_alter_calculater_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculater',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
