# Generated by Django 4.2 on 2024-11-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tixket',
            new_name='ticket',
        ),
    ]
