# Generated by Django 4.2 on 2024-12-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
