# Generated by Django 4.2 on 2024-12-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculation', '0007_delete_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.BigIntegerField()),
                ('purpose', models.CharField(default=' ', max_length=48)),
                ('lateral', models.BigIntegerField(blank=True, null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
